"use client";

import { useState, type FormEvent } from "react";
import { Bookmark, Check, Columns3, LayoutList, PanelsTopLeft, Pencil, Save, SlidersHorizontal, Trash2 } from "lucide-react";
import { Button, ConfirmDialog, Field, Input, Modal, Select, cn } from "@/components/ui";
import { ISSUE_GROUPS, ISSUE_SORTS, type IssueViewState } from "@/lib/utils/view-url";
import type { Command, SavedView, WorkspaceData } from "@/types/domain";
import { ISSUE_COLUMNS, type IssueColumn } from "./issue-list";

type ViewCommand = Extract<Command, { type: "view.save" | "view.delete" }>;

export function IssueViewControls({ data, view, onChange, columns, onColumns, activeViewId, onLoadView, onCommand, busy }: {
  data: WorkspaceData; view: IssueViewState; onChange: (patch: Partial<IssueViewState>) => void;
  columns: IssueColumn[]; onColumns: (columns: IssueColumn[]) => void; activeViewId: string | null;
  onLoadView: (view: SavedView) => void; onCommand: (command: ViewCommand) => Promise<boolean>; busy: boolean;
}) {
  const [naming, setNaming] = useState<"create" | "rename" | null>(null);
  const [name, setName] = useState("");
  const [deleting, setDeleting] = useState(false);
  const active = activeViewId ? data.savedViews[activeViewId] : undefined;
  const [formError, setFormError] = useState(false);
  async function save(event: FormEvent) {
    event.preventDefault();
    if (!name.trim()) return;
    const next = naming === "rename" && active ? { ...active, name: name.trim() } : { ...view, id: crypto.randomUUID(), name: name.trim() };
    if (await onCommand({ type: "view.save", view: next })) { setNaming(null); onLoadView(next); }
    else setFormError(true);
  }
  return <div className="flex flex-wrap items-center gap-2">
    <div className="flex rounded-lg border border-[var(--border)] bg-[var(--surface)] p-0.5" aria-label="Issue layout"><button aria-label="List view" aria-pressed={view.layout === "list"} onClick={() => onChange({ layout: "list" })} className={cn("flex items-center gap-1.5 rounded-md px-2 py-1.5 text-[11px]", view.layout === "list" ? "bg-[var(--raised)] text-[var(--text)] shadow-sm" : "text-[var(--muted)]")}><LayoutList size={13}/><span className="hidden sm:inline">List</span></button><button aria-label="Board view" aria-pressed={view.layout === "board"} onClick={() => onChange({ layout: "board" })} className={cn("flex items-center gap-1.5 rounded-md px-2 py-1.5 text-[11px]", view.layout === "board" ? "bg-[var(--raised)] text-[var(--text)] shadow-sm" : "text-[var(--muted)]")}><PanelsTopLeft size={13}/><span className="hidden sm:inline">Board</span></button></div>
    <details className="relative"><summary className="flex h-8 cursor-pointer list-none items-center gap-1.5 rounded-md border border-[var(--border)] px-2.5 text-xs text-[var(--muted)] hover:bg-[var(--raised)] [&::-webkit-details-marker]:hidden"><SlidersHorizontal size={13}/>Display</summary><div className="absolute right-0 top-10 z-30 w-64 space-y-4 rounded-xl border border-[var(--border)] bg-[var(--surface)] p-4 shadow-2xl"><Field label="Order by"><Select aria-label="Sort issues" value={view.sort} onChange={(event) => onChange({ sort: event.target.value as IssueViewState["sort"] })}>{ISSUE_SORTS.map((sort) => <option key={sort.id} value={sort.id}>{sort.name}</option>)}</Select></Field>{view.layout === "list" && <Field label="Group by"><Select aria-label="Group issues" value={view.group} onChange={(event) => onChange({ group: event.target.value as IssueViewState["group"] })}>{ISSUE_GROUPS.map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</Select></Field>}{view.layout === "board" && <p className="text-[11px] text-[var(--muted)]">Board columns always follow issue status.</p>}{view.layout === "list" && <fieldset className="space-y-2 border-t border-[var(--border)] pt-3"><legend className="flex items-center gap-2 text-xs text-[var(--muted)]"><Columns3 size={12}/>Visible columns</legend>{ISSUE_COLUMNS.map((column) => <label key={column.id} className="flex cursor-pointer items-center justify-between text-xs">{column.name}<input type="checkbox" className="accent-[var(--accent)]" checked={columns.includes(column.id)} onChange={(event) => onColumns(event.target.checked ? ISSUE_COLUMNS.filter((item) => item.id === column.id || columns.includes(item.id)).map((item) => item.id) : columns.filter((id) => id !== column.id))}/></label>)}</fieldset>}</div></details>
    <details className="relative"><summary className="flex h-8 cursor-pointer list-none items-center gap-1.5 rounded-md border border-[var(--border)] px-2.5 text-xs text-[var(--muted)] hover:bg-[var(--raised)] [&::-webkit-details-marker]:hidden"><Bookmark size={13}/><span className="max-w-24 truncate">{active?.name || "Views"}</span></summary><div className="absolute right-0 top-10 z-30 w-64 rounded-xl border border-[var(--border)] bg-[var(--surface)] p-2 shadow-2xl"><p className="px-2 py-2 text-[10px] font-semibold uppercase tracking-wider text-[var(--muted)]">Saved views</p><div className="max-h-52 overflow-y-auto">{Object.values(data.savedViews).map((saved) => <button key={saved.id} onClick={(event) => { onLoadView(saved); event.currentTarget.closest("details")?.removeAttribute("open"); }} className="flex w-full items-center gap-2 rounded-md px-2 py-2 text-left text-xs hover:bg-[var(--raised)]"><Bookmark size={12} className="text-[var(--muted)]"/><span className="min-w-0 flex-1 truncate">{saved.name}</span>{active?.id === saved.id && <Check size={12}/>}</button>)}{!Object.keys(data.savedViews).length && <p className="px-2 pb-3 text-xs text-[var(--muted)]">Keep your favorite way to see work.</p>}</div><div className="mt-1 space-y-1 border-t border-[var(--border)] pt-1"><Button size="sm" variant="ghost" className="!w-full !justify-start" onClick={() => { setName(""); setFormError(false); setNaming("create"); }}><Save size={12}/>Save as new view</Button>{active && <><Button size="sm" variant="ghost" className="!w-full !justify-start" disabled={busy} onClick={() => { void onCommand({ type: "view.save", view: { ...active, ...view } }); }}><Check size={12}/>Update this view</Button><Button size="sm" variant="ghost" className="!w-full !justify-start" onClick={() => { setName(active.name); setFormError(false); setNaming("rename"); }}><Pencil size={12}/>Rename view</Button><Button size="sm" variant="ghost" className="!w-full !justify-start !text-red-400" onClick={() => setDeleting(true)}><Trash2 size={12}/>Delete view</Button></>}</div></div></details>
    <Modal open={naming !== null} onOpenChange={(open) => { if (!open) setNaming(null); }} title={naming === "rename" ? "Rename view" : "Save your view"} description="Save filters, ordering, grouping, and layout. Project, cycle, and personal scopes stay fixed to their pages."><form onSubmit={save} className="space-y-4"><Field label="View name" htmlFor="saved-view-name"><Input id="saved-view-name" autoFocus required maxLength={80} placeholder="e.g. This week’s priorities" value={name} onChange={(event) => setName(event.target.value)}/></Field>{formError && <p role="alert" className="text-xs text-red-400">The view could not be saved. Check the error on the page and try again.</p>}<div className="flex justify-end gap-2"><Button onClick={() => setNaming(null)} variant="ghost">Cancel</Button><Button type="submit" variant="primary" disabled={!name.trim() || busy}>Save view</Button></div></form></Modal>
    <ConfirmDialog open={deleting} onOpenChange={setDeleting} title="Delete saved view?" description={`“${active?.name || "This view"}” will be removed. Your issues will not be affected.`} confirmLabel="Delete view" onConfirm={async () => { if (active && !await onCommand({ type: "view.delete", id: active.id })) throw new Error("The view could not be deleted. Please try again."); }}/>
  </div>;
}
